version: '3'
services:
  orientdb:
    image: "orientdb:latest"
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
      - ORIENTDB_NODE_NAME=odb1
    ports:
      - "2424:2424"
      - "2480:2480"
