export const CONFIG_NODE = 'Config'
export const KEY_NODE = 'Key'
export const EXTENDS_EDGE = 'EXTENDS'
export const IS_PARENT_EDGE = 'IS_PARENT'
export const HAS_KEY_EDGE = 'HAS_KEY'
export const BELONGS_TO_EDGE = 'BELONGS_TO'
